name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Cool! you have created your first issue in the project taksha."
        pr-message: "Congrats ! You have successfully contributed to the project by creating your first pull request. Keep up the good work!"
